apiVersion: v1
kind: Secret
metadata:
  name: wordpress-secrets
  namespace: default
type: Opaque
stringData:
  # MySQL root user password
  MYSQL_ROOT_PASSWORD: "root-secure-password-123"
  
  # MySQL WordPress user and password
  MYSQL_USER: "wordpress"
  MYSQL_PASSWORD: "wordpress-secure-password-456"
  
  # WordPress database name
  MYSQL_DATABASE: "wordpress"
  
  # WordPress admin credentials
  WORDPRESS_ADMIN_USER: "admin"
  WORDPRESS_ADMIN_PASSWORD: "wordpress-admin-password-789"
  WORDPRESS_ADMIN_EMAIL: "admin@work.hkhinfoteck.xyz"
